---- Default Data ----

USE Menschen
GO

-- Geschlecht --
INSERT INTO Geschlecht
	(Binär, Name, Anrede, Pronomen, GrussEndung)
VALUES
	(0, 'Keines', null , 'er/sie', '*r'),
	(1, 'Männlich', 'Herr', 'er', 'r'),
	(0, 'Divers', null, 'er/sie', '*r'),
	(1, 'Weiblich', 'Frau', 'sie', null)
GO

-- Land --
-- Source: https://de.wikipedia.org/w/index.php?title=Liste_der_Staaten_der_Erde&oldid=226239337
INSERT INTO Land
	(Name)
VALUES
	("Abchasien"),
	("Afghanistan"),
	("Ägypten"),
	("Albanien"),
	("Algerien"),
	("Andorra"),
	("Angola"),
	("Antigua und Barbuda"),
	("Äquatorialguinea"),
	("Argentinien"),
	("Armenien"),
	("Arzach"),
	("Aserbaidschan"),
	("Äthiopien"),
	("Australien"),
	("Bahamas"),
	("Bahrain"),
	("Bangladesch"),
	("Barbados"),
	("Belarus"),
	("Belgien"),
	("Belize"),
	("Benin"),
	("Bhutan"),
	("Bolivien"),
	("Bosnien und Herzegowina"),
	("Botswana"),
	("Brasilien"),
	("Brunei"),
	("Bulgarien"),
	("Burkina Faso"),
	("Burundi"),
	("Chile"),
	("Republik China"),
	("Volksrepublik China"),
	("Cookinseln"),
	("Costa Rica"),
	("Dänemark"),
	("Deutschland"),
	("Dominica"),
	("Dominikanische Republik"),
	("Dschibuti"),
	("Ecuador"),
	("El Salvador"),
	("Elfenbeinküste"),
	("Eritrea"),
	("Estland"),
	("Eswatini"),
	("Fidschi"),
	("Finnland"),
	("Frankreich"),
	("Gabun"),
	("Gambia"),
	("Georgien"),
	("Ghana"),
	("Grenada"),
	("Griechenland"),
	("Guatemala"),
	("Guinea"),
	("Guinea-Bissau"),
	("Guyana"),
	("Haiti"),
	("Honduras"),
	("Indien"),
	("Indonesien"),
	("Irak"),
	("Iran"),
	("Irland"),
	("Island"),
	("Israel"),
	("Italien"),
	("Jamaika"),
	("Japan"),
	("Jemen"),
	("Jordanien"),
	("Kambodscha"),
	("Kamerun"),
	("Kanada"),
	("Kap Verde"),
	("Kasachstan"),
	("Katar"),
	("Kenia"),
	("Kirgisistan"),
	("Kiribati"),
	("Kolumbien"),
	("Komoren"),
	("Kongo, Demokratische Republik"),
	("Kongo, Republik"),
	("Korea, Nord"),
	("Korea, Süd"),
	("Kosovo"),
	("Kroatien"),
	("Kuba"),
	("Kuwait"),
	("Laos"),
	("Lesotho"),
	("Lettland"),
	("Libanon"),
	("Liberia"),
	("Libyen"),
	("Liechtenstein"),
	("Litauen"),
	("Luxemburg"),
	("Madagaskar"),
	("Malawi"),
	("Malaysia"),
	("Malediven"),
	("Mali"),
	("Malta"),
	("Marokko"),
	("Marshallinseln"),
	("Mauretanien"),
	("Mauritius"),
	("Mexiko"),
	("Mikronesien"),
	("Moldau"),
	("Monaco"),
	("Mongolei"),
	("Montenegro"),
	("Mosambik"),
	("Myanmar"),
	("Namibia"),
	("Nauru"),
	("Nepal"),
	("Neuseeland"),
	("Nicaragua"),
	("Niederlande"),
	("Niger"),
	("Nigeria"),
	("Niue"),
	("Nordmazedonien"),
	("Nordzypern"),
	("Norwegen"),
	("Oman"),
	("Österreich"),
	("Osttimor / Timor-Leste"),
	("Pakistan"),
	("Palästina"),
	("Palau"),
	("Panama"),
	("Papua-Neuguinea"),
	("Paraguay"),
	("Peru"),
	("Philippinen"),
	("Polen"),
	("Portugal"),
	("Ruanda"),
	("Rumänien"),
	("Russland"),
	("Salomonen"),
	("Sambia"),
	("Samoa"),
	("San Marino"),
	("São Tomé und Príncipe"),
	("Saudi-Arabien"),
	("Schweden"),
	("Schweiz"),
	("Senegal"),
	("Serbien"),
	("Seychellen"),
	("Sierra Leone"),
	("Simbabwe"),
	("Singapur"),
	("Slowakei"),
	("Slowenien"),
	("Somalia"),
	("Somaliland"),
	("Spanien"),
	("Sri Lanka"),
	("St. Kitts und Nevis"),
	("St. Lucia"),
	("St. Vincent und die Grenadinen"),
	("Südafrika"),
	("Sudan"),
	("Südossetien"),
	("Südsudan"),
	("Suriname"),
	("Syrien"),
	("Tadschikistan"),
	("Tansania"),
	("Thailand"),
	("Togo"),
	("Tonga"),
	("Transnistrien"),
	("Trinidad und Tobago"),
	("Tschad"),
	("Tschechien"),
	("Tunesien"),
	("Türkei"),
	("Turkmenistan"),
	("Tuvalu"),
	("Uganda"),
	("Ukraine"),
	("Ungarn"),
	("Uruguay"),
	("Usbekistan"),
	("Vanuatu"),
	("Vatikanstadt"),
	("Venezuela"),
	("Vereinigte Arabische Emirate"),
	("Vereinigte Sta"),
	("Vereinigtes Königreich"),
	("Vietnam"),
	("Westsahara"),
	("Zentralafrikanische Republik"),
	("Zypern")